// /lessons/scale-systems-on-the-neck — part 2 of the three-part guitar
// theory track. The practical "how do I see this on the neck?" piece.
// Covers the three layer-1 systems for mapping the diatonic scale
// across all six strings: 5 pentatonic positions, 7 3NPS patterns,
// and the underrated 3-pattern "Super Duper" approach.
//
// Every pattern is drawn INLINE. Sending the reader to /builder to see
// what "position 3" looks like breaks the lesson mid-thought, so the
// diagrams live on the page and the explorer link is a secondary "go hear
// it" action. Boxes come from the same verified guitarscale.org data
// /builder uses (realizeCagedShape); the 3NPS patterns are generated by
// threeNotesPerString.

import { Link } from './components/Link';
import { Callout, Step } from './components/Step';
import { MiniNeck, type NeckDot } from './components/MiniNeck';
import {
  NeckPatternPicker,
  type NeckPattern,
} from './components/NeckPatternPicker';
import { scaleNoteLabels } from './components/labels';
import { realizeCagedShape, type RealizedPosition } from '../theory/positions';
import { threeNotesPerString } from '../theory/neck-patterns';
import { getScalePitchClasses } from '../theory/scales';
import { STANDARD_TUNING_MIDI } from '../instruments/guitar/layout';
import { pitchClassFromMidi } from '../theory/notes';
import type { PitchClass, ScaleSelection } from '../types';

/* -------------------------------------------------------------------------- */
/*  Pattern data — computed once at module scope (pure + deterministic).       */
/* -------------------------------------------------------------------------- */

const EM_PENT: ScaleSelection = { root: 'E', type: 'minorPentatonic' };
const G_MAJOR: ScaleSelection = { root: 'G', type: 'major' };

const EM_PENT_PCS = getScalePitchClasses(EM_PENT);
const G_MAJOR_PCS = getScalePitchClasses(G_MAJOR);

const emLabel = scaleNoteLabels(EM_PENT);
const gLabel = scaleNoteLabels(G_MAJOR);

/**
 * The box data anchors on the tonic, so an open-string root (E) puts
 * position 1 up at fret 12 rather than at the nut. Same shape, but drawn
 * an octave high it breaks the "the five boxes chain up the neck" story.
 * Drop it back down when the whole box clears fret 12.
 */
function toLowestOctave(positions: RealizedPosition[]): RealizedPosition[] {
  if (positions.length === 0) return positions;
  const min = Math.min(...positions.map((p) => p.fret));
  return min >= 12
    ? positions.map((p) => ({ ...p, fret: p.fret - 12 }))
    : positions;
}

function toDots(
  positions: RealizedPosition[],
  root: PitchClass,
  label: (pc: PitchClass) => string,
): NeckDot[] {
  return positions.map((p) => {
    const pc = pitchClassFromMidi(STANDARD_TUNING_MIDI[p.string] + p.fret);
    return {
      string: p.string,
      fret: p.fret,
      label: label(pc),
      root: pc === root,
    };
  });
}

function fretRange(dots: NeckDot[]): string {
  const frets = dots.map((d) => d.fret);
  const lo = Math.min(...frets);
  const hi = Math.max(...frets);
  return lo === 0 ? `open position – fret ${hi}` : `frets ${lo}–${hi}`;
}

const PENTATONIC_POSITIONS: NeckPattern[] = ([1, 2, 3, 4, 5] as const)
  .map((n) => {
    const dots = toDots(
      toLowestOctave(
        realizeCagedShape(n, 'E', EM_PENT_PCS, 'minorPentatonic'),
      ),
      'E',
      emLabel,
    );
    return {
      id: `pent-${n}`,
      label: `Position ${n}`,
      sub: `E minor pentatonic · ${fretRange(dots)} · roots in blue`,
      dots,
      theory: 'scale:E:minorPentatonic',
      sortKey: Math.min(...dots.map((d) => d.fret)),
    };
  })
  // Present them in the order your hand actually meets them going up the neck.
  .sort((a, b) => a.sortKey - b.sortKey)
  .map(({ sortKey: _sortKey, ...pattern }) => pattern);

// Every pattern is anchored at or above pattern 1's fret so the seven of
// them chain UP the neck (3, 5, 7, 8, 10, 12, 14) the way they're always
// taught. Without the floor, pattern 7 would wrap back to fret 2 — the
// same shape, but it breaks the "they stack in order" story.
const THREE_NPS_MIN_FRET = 3;

const THREE_NPS_PATTERNS: NeckPattern[] = ([0, 1, 2, 3, 4, 5, 6] as const).map(
  (degree) => {
    const dots = toDots(
      threeNotesPerString(G_MAJOR_PCS, degree, { minFret: THREE_NPS_MIN_FRET }),
      'G',
      gLabel,
    );
    return {
      id: `3nps-${degree + 1}`,
      label: `Pattern ${degree + 1}`,
      sub: `G major · starts on ${gLabel(G_MAJOR_PCS[degree])} (degree ${
        degree + 1
      }) · ${fretRange(dots)}`,
      dots,
      theory: 'scale:G:major',
    };
  },
);

// The Super Duper three: two pentatonic boxes you already know plus the
// first 3NPS pattern that fills the gap between them.
const SUPER_DUPER = [
  {
    id: 'sd-1',
    label: 'Pattern 1',
    sub: 'Pentatonic position #1 — the "Home Box"',
    description:
      'The most common shape every guitarist learns first. Anchored on the low-E-string root.',
    dots: PENTATONIC_POSITIONS[0].dots,
    theory: 'scale:E:minorPentatonic',
  },
  {
    id: 'sd-2',
    label: 'Pattern 2',
    sub: 'Pentatonic position #4 — the "A-String Home Box"',
    description:
      'Anchored on the A-string root. A second movable position you can chain off pattern 1.',
    dots: PENTATONIC_POSITIONS[3].dots,
    theory: 'scale:E:minorPentatonic',
  },
  {
    id: 'sd-3',
    label: 'Pattern 3',
    sub: 'The 1st 3-notes-per-string pattern',
    description:
      'Three notes per string, starting on the scale root on the low E. Fills the gap between the two pentatonic boxes.',
    dots: THREE_NPS_PATTERNS[0].dots,
    theory: 'scale:G:major',
  },
];

/* -------------------------------------------------------------------------- */

export default function ScaleSystemsPage() {
  return (
    <main className="mx-auto w-full px-4 py-8 sm:px-8 sm:py-12 xl:px-12">
      <header className="mb-10 max-w-3xl">
        <p className="text-xs font-semibold uppercase tracking-wide text-[var(--ink-muted)]">
          Lesson · part 2 of 3 · neck mapping
        </p>
        <h1 className="display-title mt-1 text-3xl text-[var(--ink)] sm:text-4xl">
          Mapping scales on the neck
        </h1>
        <p className="mt-3 text-sm text-[var(--ink-soft)]">
          Three different ways to see the same diatonic scale across all
          six strings. They all do the same job — pick the one that
          makes sense to your brain. Every pattern is drawn right here on
          the page; tap the pills to flip between them, and use the{' '}
          <Link to="/builder" className="underline">
            fretboard explorer
          </Link>{' '}
          link only when you want to <em>hear</em> one or try it in
          another key.
        </p>
        <p className="mt-2 text-xs text-[var(--ink-muted)]">
          Part 2 of 3 ·{' '}
          <Link
            to="/lessons/music-theory-fundamentals"
            className="underline hover:text-[var(--ink)]"
          >
            ← Part 1
          </Link>{' '}
          ·{' '}
          <Link
            to="/lessons/caged-and-roman-numerals"
            className="underline hover:text-[var(--ink)]"
          >
            Part 3 →
          </Link>
        </p>
      </header>

      {/* ----------------------------------------------------- Section 1 */}
      <Step
        number={1}
        title="The 5 pentatonic positions"
        lede="The first system. Five movable shapes, each containing 5 of
          the 7 scale tones (the pentatonic subset) at a specific
          position. Add the 2 missing notes back in to get the full
          diatonic scale at that position."
      >
        <p className="mt-3 text-sm text-[var(--ink-soft)]">
          Anchor position #1 by placing your index finger on the{' '}
          <strong>minor scale root</strong> (or pinky on the{' '}
          <strong>major scale root</strong>). The other four chain up
          the neck from there — watch the fret numbers climb as you step
          through the pills.
        </p>
        <NeckPatternPicker
          patterns={PENTATONIC_POSITIONS}
          fromFret={0}
          toFret={15}
        />
        <Callout>
          Add the 2 non-pentatonic scale tones to each position and you
          have the full 7-note diatonic scale at that position. Switch
          the scale type to <em>minor</em> in <code>/builder</code> to
          see the same positions with all 7 notes.
        </Callout>
      </Step>

      {/* ----------------------------------------------------- Section 2 */}
      <Step
        number={2}
        title="The seven 3-notes-per-string patterns"
        lede="Same job as the 5 pentatonic positions — map the diatonic
          scale across the neck — but using 7 patterns of exactly 3
          notes on each string. Each pattern starts on a different
          scale note on the low E. Pattern #1 starts on the root."
      >
        <NeckPatternPicker
          patterns={THREE_NPS_PATTERNS}
          fromFret={0}
          toFret={20}
        />
        <p className="mt-3 text-xs text-[var(--ink-muted)]">
          Notice every string carries exactly three dots — that even
          spacing is what makes these patterns fast to play and easy to
          remember. The one-fret jog on the B and high-e strings is the
          G→B tuning gap (a major 3rd instead of a 4th), not a mistake.
        </p>
        <Callout>
          When you're playing in the minor perspective of the key,
          re-number these patterns so pattern #6 (which starts on the
          Aeolian root) becomes your new #1.
        </Callout>
      </Step>

      {/* ----------------------------------------------------- Section 3 */}
      <Step
        number={3}
        title="The Super Duper Top Secret 3-pattern system"
        lede="Same job again — map the diatonic scale — but using only 3
          patterns. Underrated because there's nothing to confuse it
          with, so the internet doesn't argue about it. Two of the
          three are just patterns you already know."
      >
        <div className="mt-5 space-y-4">
          {SUPER_DUPER.map((p) => (
            <article
              key={p.id}
              className="rounded-2xl border border-[var(--line)] bg-[var(--card)] p-4 sm:p-5"
            >
              <div className="flex flex-wrap items-baseline justify-between gap-2">
                <div>
                  <div className="text-xs font-semibold uppercase tracking-wide text-[var(--ink-muted)]">
                    {p.label}
                  </div>
                  <div className="mt-0.5 text-sm font-semibold text-[var(--ink)]">
                    {p.sub}
                  </div>
                </div>
                <Link
                  to="/builder"
                  search={{ theory: p.theory }}
                  className="text-xs font-medium text-[var(--accent)] no-underline hover:underline"
                >
                  Hear it on the fretboard explorer →
                </Link>
              </div>
              <p className="mt-2 max-w-2xl text-xs text-[var(--ink-soft)]">
                {p.description}
              </p>
              <div className="mt-3 overflow-x-auto">
                <MiniNeck
                  dots={p.dots}
                  fromFret={0}
                  toFret={15}
                  ariaLabel={`${p.label} — ${p.sub}`}
                />
              </div>
            </article>
          ))}
        </div>
        <Callout>
          <strong>The point of all three systems is identical.</strong>{' '}
          Five positions, seven patterns, three patterns — they all map
          the same 7 diatonic notes across the same fretboard. Pick the
          one that makes sense to your brain and move on.
        </Callout>
      </Step>

      <footer className="mt-12 max-w-3xl rounded-2xl border border-[var(--line)] bg-[var(--bg-subtle)] p-6">
        <h2 className="text-base font-semibold text-[var(--ink)]">
          Next up
        </h2>
        <p className="mt-3 text-sm text-[var(--ink-soft)]">
          Mapping the scale is "layer 1". Next lesson is "layer 2" —
          chords. Same fretboard, different goal: how do you keep up
          with chord changes when you're soloing, and how do you
          transpose any progression to any key without thinking?
        </p>
        <div className="mt-4 flex flex-wrap gap-3">
          <Link
            to="/lessons/caged-and-roman-numerals"
            className="inline-flex items-center gap-1 rounded-full border border-[var(--accent)] bg-[var(--accent-soft)] px-4 py-1.5 text-sm font-medium text-[var(--accent)] no-underline hover:bg-[var(--accent)] hover:text-white"
          >
            Part 3: CAGED + Roman numerals →
          </Link>
          <Link
            to="/lessons"
            className="inline-flex items-center gap-1 rounded-full border border-[var(--line)] px-4 py-1.5 text-sm font-medium text-[var(--ink-muted)] no-underline hover:border-[var(--accent)] hover:text-[var(--ink)]"
          >
            Back to lessons
          </Link>
        </div>
      </footer>
    </main>
  );
}
